modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "space"
version = "${version}"
displayName = "Space"
authors = "AmbleLabs"
description = '''
Space for 1.21.1, Fabric and Forge!
'''
#logoFile = ""

[[mixins]]
config = "space.mixins.json"

[[dependencies.space]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.219,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.space]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"



